//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio.Dal.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentCategory
    {
        public DocumentCategory()
        {
            this.Documents = new HashSet<Document>();
            this.ChildCategories = new HashSet<DocumentCategory>();
            OnInit();
        }
        partial void OnInit();
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<int> Order { get; set; }
        public bool ShowDocTypeFilter { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Description { get; set; }
        public string StaticPageUrl { get; set; }
    
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<DocumentCategory> ChildCategories { get; set; }
        public virtual DocumentCategory ParentCategory { get; set; }
    }
}
