//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio.Dal.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public Document()
        {
            this.DocumentCategories = new HashSet<DocumentCategory>();
            OnInit();
        }
        partial void OnInit();
        public int Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string Name { get; set; }
        public string Number { get; set; }
        public Nullable<System.DateTime> DocumentDate { get; set; }
        public bool IsPublished { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<int> FileId { get; set; }
        public int AuthorId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> RevisionDate { get; set; }
        public string RevisionNumber { get; set; }
        public Nullable<System.DateTime> RealDocumentDate { get; set; }
        public bool IsExpired { get; set; }
    
        public virtual User User { get; set; }
        public virtual File File { get; set; }
        public virtual DocumentType DocumentType { get; set; }
        public virtual ICollection<DocumentCategory> DocumentCategories { get; set; }
    }
}
