//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio.Dal.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public File()
        {
            this.Thumbnails = new HashSet<File>();
            OnInit();
        }
        partial void OnInit();
        public int Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string OriginalName { get; set; }
        public Nullable<long> Size { get; set; }
        public string MimeType { get; set; }
        public string Description { get; set; }
        public string ContainerId { get; set; }
        public string NameInStorage { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int AuthorId { get; set; }
    
        public virtual ICollection<File> Thumbnails { get; set; }
        public virtual File ParentFile { get; set; }
    }
}
