//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio.Dal.Model
{
    using System;
    
    public partial class FullTextSearchResult
    {
        public int Id { get; set; }
        public Nullable<int> PreviewId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public ContentType EntityType { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int Rank { get; set; }
        public string SectionName { get; set; }
        public string SectionUrl { get; set; }
    }
}
