//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio.Dal.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsCategory
    {
        public NewsCategory()
        {
            OnInit();
        }
        partial void OnInit();
        public int Id { get; set; }
        public string Title { get; set; }
        public string RecentTitle { get; set; }
        public string Url { get; set; }
        public bool IsUse { get; set; }
        public int NewsPageSize { get; set; }
        public int RecentNewsPageSize { get; set; }
        public string ShortTitle { get; set; }
    }
}
