//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio.Dal.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public News()
        {
            OnInit();
        }
        partial void OnInit();
        public int Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string Title { get; set; }
        public string Announcement { get; set; }
        public string Text { get; set; }
        public bool IsPublished { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<int> ImageId { get; set; }
        public int AuthorId { get; set; }
        public Nullable<int> ThumbnailId { get; set; }
        public Nullable<int> GalleryId { get; set; }
        public bool IsDeleted { get; set; }
        public string ContainerId { get; set; }
        public bool IsGalleryVisibleInGalleries { get; set; }
        public Nullable<System.DateTime> PublishDateTo { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public bool IsPoster { get; set; }
        public Nullable<int> DependentOrganizationId { get; set; }
        public bool IsImportant { get; set; }
        public bool IsPublishInNews { get; set; }
    
        public virtual File Image { get; set; }
        public virtual File Thumbnail { get; set; }
        public virtual NewsCategory NewsCategory { get; set; }
        public virtual PhotoGallery PhotoGallery { get; set; }
        public virtual User User { get; set; }
        public virtual DependentOrganization DependentOrganization { get; set; }
    }
}
