//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio.Dal.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoGalleriesFile
    {
        public PhotoGalleriesFile()
        {
            OnInit();
        }
        partial void OnInit();
        public int PhotoGalleryId { get; set; }
        public int FileId { get; set; }
        public Nullable<int> ThumbnailId { get; set; }
        public string PhotoName { get; set; }
        public Nullable<int> OrderNumber { get; set; }
    
        public virtual File Image { get; set; }
        public virtual File Thumbnail { get; set; }
        public virtual PhotoGallery PhotoGallery { get; set; }
    }
}
